os: osx
osx_image: xcode10.1
language: objective-c
xcode_workspace: MuzeiOSX.xcworkspace
xcode_scheme: MuzeiOSX
xcode_destination: platform=macOS
env:
- EXPANDED_CODE_SIGN_IDENTITY="-"
- EXPANDED_CODE_SIGN_IDENTITY_NAME="-"
before_install:
- pod update
- pod install
script: |
  xcodebuild build -configuration release -workspace MuzeiOSX.xcworkspace -scheme MuzeiOSX CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath ./build
after_success:
- cd ./build/Build/Products/Release
- zip -9ry macOS-Muzei-continuous.zip Muzei.app
- shasum -a 256 macOS-Muzei-continuous.zip > macOS-Muzei-continuous.zip.sha256
- cd -
- mv ./build/Build/Products/Release/macOS-Muzei-continuous.zip .
- mv ./build/Build/Products/Release/macOS-Muzei-continuous.zip.sha256 .
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cHrg6FQr4OhWwZwXDrr4a0z4iWKib4waXM1JQlUtlHpGjn0cLEO0s5v+4ApjTDbfFu1jxVeK052nFTwBJ8De1TVRdQ41AYjGIBfr//ZGwD618VwOuKjSi+lfd6Wp2MadY1Dy6aWgWusxycS8MuJ2OoeQw+Xc7vTJH0DVu8uwHO30rLpJmy1svxc61C0fk9uTscxfE892FPwxR6p5M2YbAldt+/bXFqSm/PEO7wNkn/zjQTVNnz1Svn2DzDHPTQ+2z4yixVquP1C60nXlYnI1KS5LAKHUxqHYnTPMcbYv31650g1IipLK1nLX6auv7blZFAuYgSgneC47SuiDqFjQnXTG7gKJKyexKkJaEzLV7+sctHE6WwmV4dYI3b/QPbjijhfjdxzGojU5fFu7M7om/fCoyQx8sMfJmZxXBzQc9LaKcnqAw/xq+xv2sLgBunZT4Q/BaPEFXfjG9GgYolDCnOKhbLo9zyV9GgwgX84V7zbK96e+Acy8RF6wAKqN84xg0tOhzfy7neLjRS1GKsA+Ogc9fo2RS88MTN37PcGNuc2HJVh8VWt3TfHxbE/yM+f9Vk5MZOT97X32CRorUoEL2Ve+HZ0u0mO+c7TB52P0mIO4lFhVeladH3rib/V/Dxx1TbGvVVBixQP5YuT2i+VD8EKOcfwW0yX/aCwKspnCAW0=
  file:
    - macOS-Muzei-continuous.zip
    - macOS-Muzei-continuous.zip.sha256
  on:
    repo: dotWee/macOS-Muzei
    branch: master